// Code generated by @open-rpc/generator DO NOT EDIT or ur gonna have a bad tiem
import { IMethodMapping } from "@open-rpc/server-js/build/router";

import methods from "./methods";

export const methodMapping: IMethodMapping = {
  hello: methods.hello,
};

export default methodMapping;
